server:
  port: 8089
  servlet:
    context-path: /fucking-world
spring:
  application:
    name: fucking-world
    path: /fucking-world
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #    username: wl
    #    password: qwer1234
    #    url: jdbc:oracle:thin:@localhost:1521:orcl
    #    driver-class-name: oracle.jdbc.OracleDriver
    username: WL
    password: 1234zxcv
    # url 可以不加数据库名但是实体类的table name注解要加数据库名
    url: jdbc:mysql://192.168.1.6:3306?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间(毫秒)
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置有一个连接在连接池中的最小生存时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql将无法统计，'wall'用于防火墙
      filters: stat, wall, log4j
      # 通过connectProperties属性来打开mergeSql功能，慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      logType: slf4j
      # 配置监控服务器
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 1000
    lettuce:
      pool:
        max-active: 32
        max-wait: -1
        max-idle: 16
        min-idle: 8
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure:
            logging: info
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
netty:
  server:
    port: 8090
    bossThreads: 1
pattern:
  dateformat: aann
psr:
  gateway:
    tUrl: http://localhsot:321/test2