USE blbl;
DROP TABLE IF EXISTS T_USER_COMMENT;
CREATE TABLE T_USER_COMMENT(
    CID INT NOT NULL PRIMARY KEY ,
    PREV_COMMENT INT,
    USER_ID INT,
    RELATE_COMMENT INT,
    CONTENT VARCHAR(1000),
    VIDEO_ID INT,
    COMMENT_TIME TIMESTAMP
);

