USE fucking_world;
DROP TABLE IF EXISTS fucking_user_comment;
CREATE TABLE fucking_user_comment(
    CID INT NOT NULL PRIMARY KEY ,
    PREV_COMMENT INT,
    USER_ID INT,
    RELATE_COMMENT INT,
    CONTENT VARCHAR(1000),
    VIDEO_ID INT,
    COMMENT_TIME TIMESTAMP
);

